# Generated by Django 5.2.6 on 2025-10-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_info',
            field=models.CharField(null=True, verbose_name='ShortInfo'),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(null=True, verbose_name='Topic'),
        ),
    ]
