# Generated by Django 5.2.6 on 2025-10-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_short_info_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='photo_test.jpg', upload_to=''),
        ),
    ]
