# Generated by Django 5.2.6 on 2025-10-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
